### ISSUE TITLE
You must have Elite status to teleport to a custom location.

### ISSUE THREAD

**Issue by PotehtoO** [Owyn/infinity-journal#1]
I hope I'm not disturbing you, but a similar issue with a recent issue request you'd submitted on another journal module occurred; I've tried to seek out what's causing the issue, if it's just a lack of the regional journal's ID, upon looking for and adding it, it didn't seem to help, toolbox console doesn't seem to list any errors either ㅠㅠ

The region in question is SEA btw, a recent update for GVHM seems to have bork journal modules somehow 😢

**Comment by Owyn** [comment]
Yes it was lack of the regional journal's ID, try pressing your journal\atlas with turned on https://github.com/Owyn/PacketsLogger and see the id for yourself

**Comment by PotehtoO** [comment]
I've tried, but was either sadly unable to find the ID or it was just the wrong one. I hope it's okay to ask, but is the ID I'll want to look for under  ` "item": XXXXXX ` in the ` C_REQUEST_NONDB_ITEM_INFO `

line/area? I've tried to get the code from there into the index.js but it still doesn't seem to work ><

**Comment by Owyn** [comment]
S_PCBANGINVENTORY_DATALIST
C_PCBANGINVENTORY_USE_SLOT

**Comment by PotehtoO** [comment]
Those values don't seem to show up on SEA for some reason, however, I've gotten on NA to check and while `C_PCBANGINVENTORY_USE_SLOT ` shows up, it doesn't show anything more than `"slot": 2`, the journal/atlas ID's show up but they're listed under `C_REQUEST_NONDB_ITEM_INFO` as well.

Taking the similar codes under those values on SEA to add it to the journal doesn't seem to fix it though. Well, I really don't want to bother/disturb you do work on the SEA region, but if you've got plans to do so- or if there's anything I can do to help make fixing it easier I'll do what I can ><

**Comment by Owyn** [comment]
`S_PCBANGINVENTORY_DATALIST` should have it for sure
make sure to use `logblackclear` in packetslogger

**Comment by PotehtoO** [comment]
![Untitled-1](https://user-images.githubusercontent.com/37375153/58373627-8583ad80-7f63-11e9-90db-361674a1a925.jpg)

These were what I was able to get after clearing the blacklist and attempting to log using atlas/journal, I get a lot of null(id)'s for some reason- even when I'm trying to log on a fresh copy of toolbox. I've tried the ID's that looked like they belonged to the atlas/journal (`854567, 855598`) but the error still persists sadly ㅠㅠ

**Comment by Owyn** [comment]
If those ids actually belonged to your atlas\journal, module would have worked fine for you

S_PCBANGINVENTORY_DATALIST is sent when you enter a character, so you need logging enabled before that

**Comment by PotehtoO** [comment]
So I've went ahead and tried logging NA packets comparing them with packets logged on SEA using the same methods, `logBlackClear` then `logC` and `logS` and then `logBlackClear` again, relog the same character then use atlas/journal. The packets seem to show up fine for NA but oddly enough, it refuses to appear on the logging for SEA. I can't really find out the cause but is it possible that the region's publishers have done something to prevent it from showing up?

![Untitled-1](https://user-images.githubusercontent.com/37375153/58375515-49fada80-7f87-11e9-8934-da8a6ce6bf3a.jpg)

I don't want to trouble you but I guess I'm just out of ideas and am unsure of what I'm doing/need to do at this point, so I'm just wondering if you have plans for working on journal for SEA region at some point in the future maybe ;-;

**Comment by Owyn** [comment]
does SEA even have S_PCBANGINVENTORY_DATALIST  opcode mapped?

if they changed the mechanism somehow, but C_PCBANGINVENTORY_USE_SLOT is still used, you could just hardcode slot numbers to be used instead of finding the item id in the DATALIST, if you really want to make journal work on SEA

**Comment by PotehtoO** [comment]
How would one go about checking if S_PCBANGINVENTORY_DATALIST is mapped? There may be a chance it isn't I suppose- since it very recently got the GVHM patch update(prior to that update it still worked fine).

I'm unsure if C_PCBANGINVENTORY_USE_SLOT is in there either, in the above comment where I mentioned I was able to find it that was when trying to log NA to reference sadly. Is there a chance this means that journal is just not going to be usable on SEA? :c

**Comment by Owyn** [comment]
check file for your protocol in here https://github.com/tera-toolbox/tera-data/tree/master/map_base

**Comment by PotehtoO** [comment]
Ahh, looks like it's not mapped then, neither of the PCBANG lines seem to appear in the SEA opcodes >-< Well, thanks so far though, guess I've at least learned a few things here and there :')

**Comment by Owyn** [comment]
there's another `DATALIST` there, perhaps they simply renamed it

**Comment by PotehtoO** [comment]
Seems to be- yeah. Turns out the IDs do show under `S_PREMIUM_SLOT_DATALIST` and `C_PCBANGINVENTORY_USE_SLOT` was also replaced/renamed with `C_USE_PREMIUM_SLOT` instead. Would this mean simply changing the `C_PCBANGINVENTORY_USE_SLOT` and `S_PCBANGINVENTORY_DATALIST` in index.js will allow the journal module to work, along with adding the IDs in as well?

**Comment by Owyn** [comment]
if they are exactly same (renamed) you could just add their opcodes under old names `C_PCBANGINVENTORY_USE_SLOT` and it'd work without any index.js edits

**Comment by Owyn** [comment]
But thet aren't the same so you shouldn't do that https://github.com/tera-toolbox/tera-data/commit/8c8291185355916ec7a0f79be9d465f61d762ddf

**Comment by Owyn** [comment]
Try new version btw, people said it works fine
